#spring.application.name=Gestion-des-utilisateurs

server.port: 8080

spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/todolist?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:postgresql://localhost:5432/usermanagment
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  ## Specify DBMS
  jpa:
    #    database: MYSQL
    database: postgresql
    show-sql: false
    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: uneCléSecrèteTrèsLongueEtSécurisée
  expiration: 86400000 # (24h en millisecondes)


